Data Analysis

In [25]:
import numpy as np
import pandas as pd

In [85]:
df = pd.read_csv("heart.csv")

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    str
 2   ChestPainType   918 non-null    str
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    str
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    str
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), str(5)
memory usage: 86.2 KB

In [87]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [29]:
df.describe(include="all")

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,918.000000,918,918,918.000000,918.000000,918.000000,918,918.000000,918,918.000000,918,918.000000
unique,NaN,2,4,NaN,NaN,NaN,3,NaN,2,NaN,3,NaN
top,NaN,M,ASY,NaN,NaN,NaN,Normal,NaN,N,NaN,Flat,NaN
freq,NaN,725,496,NaN,NaN,NaN,552,NaN,547,NaN,460,NaN
mean,53.510893,NaN,NaN,132.396514,198.799564,0.233115,NaN,136.809368,NaN,0.887364,NaN,0.553377
std,9.432617,NaN,NaN,18.514154,109.384145,0.423046,NaN,25.460334,NaN,1.066570,NaN,0.497414
min,28.000000,NaN,NaN,0.000000,0.000000,0.000000,NaN,60.000000,NaN,-2.600000,NaN,0.000000
25%,47.000000,NaN,NaN,120.000000,173.250000,0.000000,NaN,120.000000,NaN,0.000000,NaN,0.000000
50%,54.000000,NaN,NaN,130.000000,223.000000,0.000000,NaN,138.000000,NaN,0.600000,NaN,1.000000
75%,60.000000,NaN,NaN,140.000000,267.000000,0.000000,NaN,156.000000,NaN,1.500000,NaN,1.000000
max,77.000000,NaN,NaN,200.000000,603.000000,1.000000,NaN,202.000000,NaN,6.200000,NaN,1.000000

In [30]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [31]:
df.duplicated().sum()

np.int64(0)

In [32]:
df.nunique()

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [33]:
cat_col = df.select_dtypes(include="object").columns
print(cat_col)

Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='str')

C:\Users\shivp\AppData\Local\Temp\ipykernel_18568\3251956230.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_col = df.select_dtypes(include="object").columns

converting catagorical into numrical 
sex: male-0 female,-1
chestpaintype: ATA-0,NAP-1,ASY-2,TA-3
RestingECG: normal-0,ST-1,LVH-2
ExerciseAnigna: N-0,Y-1
ST-Slope:up-0,flat-1,down-2

In [34]:
# Define the mapping for each categorical column
mappings = {
    'Sex': {'M': 0, 'F': 1},
    'ChestPainType': {'ATA': 0, 'NAP': 1, 'ASY': 2, 'TA': 3},
    'RestingECG': {'Normal': 0, 'ST': 1, 'LVH': 2},
    'ExerciseAngina': {'N': 0, 'Y': 1},
    'ST_Slope': {'Up': 0, 'Flat': 1, 'Down': 2}
}
# Apply all mappings at once
df.replace(mappings, inplace=True)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,0,0,140,289,0,0,172,0,0.0,0,0
1,49,1,1,160,180,0,0,156,0,1.0,1,1
2,37,0,0,130,283,0,1,98,0,0.0,0,0
3,48,1,2,138,214,0,0,108,1,1.5,1,1
4,54,0,1,150,195,0,0,122,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,0,3,110,264,0,0,132,0,1.2,1,1
914,68,0,2,144,193,1,0,141,0,3.4,1,1
915,57,0,2,130,131,0,0,115,1,1.2,1,1
916,57,1,0,130,236,0,2,174,0,0.0,1,1
917,38,0,1,138,175,0,0,173,0,0.0,0,0

In [35]:
df['Cholesterol'].value_counts()
df['Cholesterol'].replace(0, np.nan, inplace=True)

C:\Users\shivp\AppData\Local\Temp\ipykernel_18568\4023379399.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Cholesterol'].replace(0, np.nan, inplace=True)

0      289.0
1      180.0
2      283.0
3      214.0
4      195.0
       ...
913    264.0
914    193.0
915    131.0
916    236.0
917    175.0
Name: Cholesterol, Length: 918, dtype: float64

In [36]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(df)
df= pd.DataFrame(after_impute, columns=df.columns)

In [37]:
df['Cholesterol'].isna().sum()

np.int64(0)

In [38]:
df['RestingBP'][df['RestingBP'] == 0]

449    0.0
Name: RestingBP, dtype: float64

In [39]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(df)
df_imputed = pd.DataFrame(after_impute, columns=df.columns)

In [40]:
df['RestingBP'].isnull().sum()

np.int64(0)

In [41]:
withoutOldpeak = df.columns
withoutOldpeak = withoutOldpeak.drop('Oldpeak')
df[withoutOldpeak] = df[withoutOldpeak].astype('Int32')

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    Int32
 1   Sex             918 non-null    Int32
 2   ChestPainType   918 non-null    Int32
 3   RestingBP       918 non-null    Int32
 4   Cholesterol     918 non-null    Int32
 5   FastingBS       918 non-null    Int32
 6   RestingECG      918 non-null    Int32
 7   MaxHR           918 non-null    Int32
 8   ExerciseAngina  918 non-null    Int32
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    Int32
 11  HeartDisease    918 non-null    Int32
dtypes: Int32(11), float64(1)
memory usage: 56.6 KB

In [43]:
df.sample()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
358,38,0,1,115,0,0,0,128,1,0.0,1,1

In [44]:
df.corr()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
Age,1.000000,-0.055750,0.214164,0.254399,-0.095282,0.198039,0.213152,-0.382045,0.215793,0.258612,0.268264,0.282039
Sex,-0.055750,1.000000,-0.179766,-0.005133,0.200092,-0.120076,0.018343,0.189186,-0.190664,-0.105734,-0.150693,-0.305445
ChestPainType,0.214164,-0.179766,1.000000,0.075332,-0.130997,0.155111,0.112067,-0.273076,0.324049,0.300846,0.352364,0.459017
RestingBP,0.254399,-0.005133,0.075332,1.000000,0.100893,0.070193,0.097661,-0.112135,0.155101,0.164803,0.075162,0.107589
Cholesterol,-0.095282,0.200092,-0.130997,0.100893,1.000000,-0.260974,0.112095,0.235792,-0.034166,0.050148,-0.111471,-0.232741
FastingBS,0.198039,-0.120076,0.155111,0.070193,-0.260974,1.000000,0.050707,-0.131438,0.060451,0.052698,0.175774,0.267291
RestingECG,0.213152,0.018343,0.112067,0.097661,0.112095,0.050707,1.000000,0.048552,0.036119,0.114428,0.078807,0.061011
MaxHR,-0.382045,0.189186,-0.273076,-0.112135,0.235792,-0.131438,0.048552,1.000000,-0.370425,-0.160691,-0.343419,-0.400421
ExerciseAngina,0.215793,-0.190664,0.324049,0.155101,-0.034166,0.060451,0.036119,-0.370425,1.000000,0.408752,0.428706,0.494282
Oldpeak,0.258612,-0.105734,0.300846,0.164803,0.050148,0.052698,0.114428,-0.160691,0.408752,1.000000,0.501921,0.403951
ST_Slope,0.268264,-0.150693,0.352364,0.075162,-0.111471,0.175774,0.078807,-0.343419,0.428706,0.501921,1.000000,0.558771
HeartDisease,0.282039,-0.305445,0.459017,0.107589,-0.232741,0.267291,0.061011,-0.400421,0.494282,0.403951,0.558771,1.000000

Visualization of dataset

In [45]:
import plotly.express as px
px.line(df.corr()['HeartDisease'][:-1].sort_values())

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'variable=HeartDisease<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'HeartDisease',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'HeartDisease',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['MaxHR', 'Sex', 'Cholesterol', 'RestingECG', 'RestingBP', 'FastingBS',
                          'Age', 'Oldpeak', 'ChestPainType', 'ExerciseAngina', 'ST_Slope'],
                         dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('ovJeb36g2b9OojLVaIzTv94hUvxxys' ... 'KIYN0/J8R471Ci3z+tvkcfc+HhPw=='),
                    'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'variable'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'index'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'value'}}}
})

In [46]:
px.sunburst(df,path=['HeartDisease','Age'])

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'branchvalues': 'total',
              'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hovertemplate': 'labels=%{label}<br>count=%{value}<br>parent=%{parent}<br>id=%{id}<extra></extra>',
              'ids': array(['0/40', '1/49', '0/37', '1/48', '0/54', '0/39', '0/45', '1/37', '0/48',
                            '1/58', '0/42', '1/38', '0/43', '1/60', '1/36', '0/44', '0/49', '1/44',
                            '0/36', '0/53', '0/52', '0/51', '1/53', '0/56', '1/54', '1/41', '0/32',
                            '1/65', '0/41', '0/35', '1/43', '0/59', '0/50', '1/50', '1/47', '1/31',
                            '1/52', '1/46', '1/57', '1/55', '0/46', '1/32', '0/55', '1/63', '1/56',
                            '1/66', '1/40', '0/57', '0/34', '0/47', '0/38', '1/33', '1/59', '1/34',
                            '0/58', '0/61', '0/29', '0/62', '0/31', '1/35', '0/28', '0/30', '1/39',
                            '1/51', '0/33', '1/45', '0/60', '1/61', '1/62', '0/65', '1/74', '1/68',
                            '1/42', '0/72', '1/64', '1/69', '1/67', '1/73', '1/70', '0/66', '0/63',
                            '0/74', '1/77', '1/72', '1/75', '0/64', '1/76', '0/68', '1/71', '0/75',
                            '0/69', '0/67', '0/71', '0/70', '0/76', '0', '1'], dtype=object),
              'labels': array(['40', '49', '37', '48', '54', '39', '45', '37', '48', '58', '42', '38',
                               '43', '60', '36', '44', '49', '44', '36', '53', '52', '51', '53', '56',
                               '54', '41', '32', '65', '41', '35', '43', '59', '50', '50', '47', '31',
                               '52', '46', '57', '55', '46', '32', '55', '63', '56', '66', '40', '57',
                               '34', '47', '38', '33', '59', '34', '58', '61', '29', '62', '31', '35',
                               '28', '30', '39', '51', '33', '45', '60', '61', '62', '65', '74', '68',
                               '42', '72', '64', '69', '67', '73', '70', '66', '63', '74', '77', '72',
                               '75', '64', '76', '68', '71', '75', '69', '67', '71', '70', '76', '0',
                               '1'], dtype=object),
              'name': '',
              'parents': array(['0', '1', '0', '1', '0', '0', '0', '1', '0', '1', '0', '1', '0', '1',
                                '1', '0', '0', '1', '0', '0', '0', '0', '1', '0', '1', '1', '0', '1',
                                '0', '0', '1', '0', '0', '1', '1', '1', '1', '1', '1', '1', '0', '1',
                                '0', '1', '1', '1', '1', '0', '0', '0', '0', '1', '1', '1', '0', '0',
                                '0', '0', '0', '1', '0', '0', '1', '1', '0', '1', '0', '1', '1', '0',
                                '1', '1', '1', '0', '1', '1', '1', '1', '1', '0', '0', '0', '1', '1',
                                '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '0', '', ''],
                               dtype=object),
              'type': 'sunburst',
              'values': {'bdata': ('BwALAAoADwAcAA0ADwABABAAHAAPAA' ... 'EABAACAAEAAwADAAMAAQABAJoB/AE='),
                         'dtype': 'i2'}}],
    'layout': {'legend': {'tracegroupgap': 0}, 'margin': {'t': 60}, 'template': '...'}
})

In [47]:
px.histogram(df,x='Age',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>Age=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('KAAAACUAAAA2AAAAJwAAAC0AAAA2AA' ... 'AAOAAAADgAAAA3AAAAKQAAACYAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>Age=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('MQAAADAAAAAlAAAAOgAAADEAAAAmAA' ... 'A5AAAALQAAAEQAAAA5AAAAOQAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Age'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [48]:
px.pie(df, names='HeartDisease', title='Distribution of Heart Disease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hovertemplate': 'HeartDisease=%{label}<extra></extra>',
              'labels': {'bdata': ('AAAAAAEAAAAAAAAAAQAAAAAAAAAAAA' ... 'AAAAEAAAABAAAAAQAAAAEAAAAAAAAA'),
                         'dtype': 'i4'},
              'legendgroup': '',
              'name': '',
              'showlegend': True,
              'type': 'pie'}],
    'layout': {'legend': {'tracegroupgap': 0}, 'template': '...', 'title': {'text': 'Distribution of Heart Disease'}}
})

In [49]:
px.histogram(df,x='Sex',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>Sex=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAEAAAAAAA' ... 'AAAAAAAAAAAAABAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>Sex=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AQAAAAEAAAAAAAAAAAAAAAAAAAAAAA' ... 'ABAAAAAAAAAAAAAAAAAAAAAQAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Sex'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [50]:
px.histogram(df,x='ChestPainType',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>ChestPainType=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAABAAAAAQAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAEAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>ChestPainType=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AQAAAAIAAAACAAAAAAAAAAIAAAACAA' ... 'ACAAAAAwAAAAIAAAACAAAAAAAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'ChestPainType'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [51]:
px.sunburst(df,path=['HeartDisease','RestingBP'])

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'branchvalues': 'total',
              'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hovertemplate': 'labels=%{label}<br>count=%{value}<br>parent=%{parent}<br>id=%{id}<extra></extra>',
              'ids': array(['0/140', '1/160', '0/130', '1/138', '0/150', '0/120', '0/110', '1/140',
                            '1/136', '0/115', '1/110', '1/100', '1/120', '0/100', '0/124', '1/150',
                            '0/113', '0/125', '1/145', '1/125', '1/130', '0/112', '0/160', '1/112',
                            '0/132', '1/118', '1/170', '0/142', '0/190', '1/135', '1/180', '0/108',
                            '0/145', '1/115', '1/155', '1/128', '0/135', '0/180', '0/170', '1/106',
                            '1/92', '1/200', '1/122', '0/122', '0/98', '0/105', '0/133', '1/95',
                            '1/105', '0/155', '0/80', '1/137', '1/185', '1/165', '1/132', '1/142',
                            '0/126', '1/133', '0/152', '1/116', '0/138', '1/124', '1/0', '1/144',
                            '0/154', '1/134', '0/104', '1/139', '0/128', '1/131', '0/134', '1/152',
                            '1/126', '1/154', '1/141', '0/131', '1/178', '1/146', '1/158', '0/106',
                            '0/136', '0/123', '1/102', '1/96', '0/139', '1/143', '1/104', '1/172',
                            '1/156', '0/118', '1/190', '0/114', '1/127', '0/101', '1/174', '1/108',
                            '0/156', '0/94', '0/148', '0/178', '1/117', '1/192', '1/123', '0/129',
                            '0/102', '0/172', '0/146', '1/148', '1/114', '1/164', '0', '1'],
                           dtype=object),
              'labels': array(['140', '160', '130', '138', '150', '120', '110', '140', '136', '115',
                               '110', '100', '120', '100', '124', '150', '113', '125', '145', '125',
                               '130', '112', '160', '112', '132', '118', '170', '142', '190', '135',
                               '180', '108', '145', '115', '155', '128', '135', '180', '170', '106',
                               '92', '200', '122', '122', '98', '105', '133', '95', '105', '155', '80',
                               '137', '185', '165', '132', '142', '126', '133', '152', '116', '138',
                               '124', '0', '144', '154', '134', '104', '139', '128', '131', '134',
                               '152', '126', '154', '141', '131', '178', '146', '158', '106', '136',
                               '123', '102', '96', '139', '143', '104', '172', '156', '118', '190',
                               '114', '127', '101', '174', '108', '156', '94', '148', '178', '117',
                               '192', '123', '129', '102', '172', '146', '148', '114', '164', '0', '1'],
                              dtype=object),
              'name': '',
              'parents': array(['0', '1', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '1', '0',
                                '0', '1', '0', '0', '1', '1', '1', '0', '0', '1', '0', '1', '1', '0',
                                '0', '1', '1', '0', '0', '1', '1', '1', '0', '0', '0', '1', '1', '1',
                                '1', '0', '0', '0', '0', '1', '1', '0', '0', '1', '1', '1', '1', '1',
                                '0', '1', '0', '1', '0', '1', '1', '1', '0', '1', '0', '1', '0', '1',
                                '0', '1', '1', '1', '1', '0', '1', '1', '1', '0', '0', '0', '1', '1',
                                '0', '1', '1', '1', '1', '0', '1', '0', '1', '0', '1', '1', '0', '0',
                                '0', '0', '1', '1', '1', '0', '0', '0', '0', '1', '1', '1', '', ''],
                               dtype=object),
              'type': 'sunburst',
              'values': {'bdata': ('NAAiAEIABwAZAE0AGgA3AAoABAAgAA' ... 'EAAQABAAIAAQABAAEAAQABAJoB/AE='),
                         'dtype': 'i2'}}],
    'layout': {'legend': {'tracegroupgap': 0}, 'margin': {'t': 60}, 'template': '...'}
})

In [52]:
px.histogram(df,x='FastingBS',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>FastingBS=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>FastingBS=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAEAAAAAAAAAAAAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'FastingBS'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [54]:
px.sunburst(df,path=['HeartDisease','MaxHR'])

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'branchvalues': 'total',
              'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hovertemplate': 'labels=%{label}<br>count=%{value}<br>parent=%{parent}<br>id=%{id}<extra></extra>',
              'ids': array(['0/172', '1/156', '0/98', '1/108', '0/122', '0/170', '0/142', '1/130',
                            '0/120', '1/99', '0/145', '1/140', '0/137', '0/150', '1/166', '0/165',
                            '1/125', '1/160', '0/164', '1/150', '0/138', '0/178', '0/112', '0/118',
                            '0/127', '0/114', '1/122', '0/154', '0/155', '1/87', '0/148', '0/130',
                            '1/100', '0/168', '1/120', '0/184', '1/170', '1/121', '1/98', '0/140',
                            '1/153', '0/134', '1/96', '0/174', '0/175', '0/144', '1/82', '1/145',
                            '0/135', '0/115', '1/128', '0/116', '0/160', '1/115', '1/94', '1/112',
                            '1/155', '0/110', '1/92', '0/180', '0/100', '1/152', '1/124', '0/106',
                            '0/124', '0/125', '0/185', '1/180', '0/139', '1/110', '0/190', '0/152',
                            '1/175', '0/146', '1/118', '1/158', '0/132', '0/176', '1/119', '0/188',
                            '0/162', '1/134', '1/135', '1/105', '0/90', '1/138', '0/136', '1/116',
                            '0/128', '0/158', '0/167', '0/129', '1/136', '1/102', '1/142', '1/143',
                            '1/103', '1/91', '1/126', '0/126', '0/156', '1/93', '1/127', '1/139',
                            '1/131', '1/149', '1/123', '1/182', '1/176', '1/154', '0/141', '1/148',
                            '1/77', '1/109', '1/133', '0/179', '1/144', '1/114', '1/113', '1/104',
                            '1/95', '1/72', '0/97', '1/117', '1/86', '1/63', '1/157', '1/83',
                            '1/60', '1/70', '1/163', '1/67', '1/78', '1/90', '0/99', '1/141',
                            '0/86', '1/84', '1/106', '1/111', '1/129', '0/133', '0/131', '1/80',
                            '1/165', '0/111', '0/107', '1/97', '0/161', '0/69', '0/80', '1/88',
                            '0/153', '1/132', '1/162', '1/73', '1/159', '0/96', '0/151', '0/105',
                            '0/121', '0/159', '0/181', '0/143', '0/157', '0/186', '1/181', '0/163',
                            '1/177', '0/173', '0/169', '0/171', '0/149', '1/147', '1/169', '1/168',
                            '1/71', '1/161', '0/192', '0/182', '1/195', '1/173', '1/174', '1/146',
                            '0/194', '0/147', '1/171', '0/187', '0/166', '0/202', '0/123', '1/164',
                            '0', '1'], dtype=object),
              'labels': array(['172', '156', '98', '108', '122', '170', '142', '130', '120', '99',
                               '145', '140', '137', '150', '166', '165', '125', '160', '164', '150',
                               '138', '178', '112', '118', '127', '114', '122', '154', '155', '87',
                               '148', '130', '100', '168', '120', '184', '170', '121', '98', '140',
                               '153', '134', '96', '174', '175', '144', '82', '145', '135', '115',
                               '128', '116', '160', '115', '94', '112', '155', '110', '92', '180',
                               '100', '152', '124', '106', '124', '125', '185', '180', '139', '110',
                               '190', '152', '175', '146', '118', '158', '132', '176', '119', '188',
                               '162', '134', '135', '105', '90', '138', '136', '116', '128', '158',
                               '167', '129', '136', '102', '142', '143', '103', '91', '126', '126',
                               '156', '93', '127', '139', '131', '149', '123', '182', '176', '154',
                               '141', '148', '77', '109', '133', '179', '144', '114', '113', '104',
                               '95', '72', '97', '117', '86', '63', '157', '83', '60', '70', '163',
                               '67', '78', '90', '99', '141', '86', '84', '106', '111', '129', '133',
                               '131', '80', '165', '111', '107', '97', '161', '69', '80', '88', '153',
                               '132', '162', '73', '159', '96', '151', '105', '121', '159', '181',
                               '143', '157', '186', '181', '163', '177', '173', '169', '171', '149',
                               '147', '169', '168', '71', '161', '192', '182', '195', '173', '174',
                               '146', '194', '147', '171', '187', '166', '202', '123', '164', '0', '1'],
                              dtype=object),
              'name': '',
              'parents': array(['0', '1', '0', '1', '0', '0', '0', '1', '0', '1', '0', '1', '0', '0',
                                '1', '0', '1', '1', '0', '1', '0', '0', '0', '0', '0', '0', '1', '0',
                                '0', '1', '0', '0', '1', '0', '1', '0', '1', '1', '1', '0', '1', '0',
                                '1', '0', '0', '0', '1', '1', '0', '0', '1', '0', '0', '1', '1', '1',
                                '1', '0', '1', '0', '0', '1', '1', '0', '0', '0', '0', '1', '0', '1',
                                '0', '0', '1', '0', '1', '1', '0', '0', '1', '0', '0', '1', '1', '1',
                                '0', '1', '0', '1', '0', '0', '0', '0', '1', '1', '1', '1', '1', '1',
                                '1', '0', '0', '1', '1', '1', '1', '1', '1', '1', '1', '1', '0', '1',
                                '1', '1', '1', '0', '1', '1', '1', '1', '1', '1', '0', '1', '1', '1',
                                '1', '1', '1', '1', '1', '1', '1', '1', '0', '1', '0', '1', '1', '1',
                                '1', '0', '0', '1', '1', '0', '0', '1', '0', '0', '0', '1', '0', '1',
                                '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0',
                                '1', '0', '0', '0', '0', '1', '1', '1', '1', '1', '0', '0', '1', '1',
                                '1', '1', '0', '0', '1', '0', '0', '0', '0', '1', '', ''], dtype=object),
              'type': 'sunburst',
              'values': {'bdata': ('CgAGAAIACAAFAA4ACQAWAAsABgAFAB' ... 'ABAAIAAQABAAIAAQABAAEAmgH8AQ=='),
                         'dtype': 'i2'}}],
    'layout': {'legend': {'tracegroupgap': 0}, 'margin': {'t': 60}, 'template': '...'}
})

In [55]:
px.violin(df, y='MaxHR', x='HeartDisease',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'box': {'visible': False},
              'hovertemplate': 'HeartDisease=%{x}<br>MaxHR=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa'},
              'name': '0',
              'offsetgroup': '0',
              'orientation': 'v',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('rAAAAGIAAAB6AAAAqgAAAKoAAACOAA' ... 'AAowAAAKkAAACmAAAAtgAAAK0AAAA='),
                    'dtype': 'i4'},
              'y0': ' ',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'box': {'visible': False},
              'hovertemplate': 'HeartDisease=%{x}<br>MaxHR=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B'},
              'name': '1',
              'offsetgroup': '1',
              'orientation': 'v',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': {'bdata': ('AQAAAAEAAAABAAAAAQAAAAEAAAABAA' ... 'ABAAAAAQAAAAEAAAABAAAAAQAAAA=='),
                    'dtype': 'i4'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('nAAAAGwAAACCAAAAYwAAAIwAAACmAA' ... 'B7AAAAhAAAAI0AAABzAAAArgAAAA=='),
                    'dtype': 'i4'},
              'y0': ' ',
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'violinmode': 'overlay',
               'xaxis': {'anchor': 'y',
                         'categoryarray': [0, 1],
                         'categoryorder': 'array',
                         'domain': [0.0, 1.0],
                         'title': {'text': 'HeartDisease'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'MaxHR'}}}
})

In [56]:
px.violin(df, y='Oldpeak', x='HeartDisease', color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'box': {'visible': False},
              'hovertemplate': 'HeartDisease=%{x}<br>Oldpeak=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa'},
              'name': '0',
              'offsetgroup': '0',
              'orientation': 'v',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'MzM/M/AAAAAAAAAAAAAAAAAAAAAA=='),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'box': {'visible': False},
              'hovertemplate': 'HeartDisease=%{x}<br>Oldpeak=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B'},
              'name': '1',
              'offsetgroup': '1',
              'orientation': 'v',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': {'bdata': ('AQAAAAEAAAABAAAAAQAAAAEAAAABAA' ... 'ABAAAAAQAAAAEAAAABAAAAAQAAAA=='),
                    'dtype': 'i4'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('AAAAAAAA8D8AAAAAAAD4PwAAAAAAAP' ... 'MzMzMLQDMzMzMzM/M/AAAAAAAAAAA='),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'violinmode': 'overlay',
               'xaxis': {'anchor': 'y',
                         'categoryarray': [0, 1],
                         'categoryorder': 'array',
                         'domain': [0.0, 1.0],
                         'title': {'text': 'HeartDisease'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Oldpeak'}}}
})

In [57]:
px.histogram(df,x='ST_Slope',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>ST_Slope=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAIAAAAAAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>ST_Slope=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AQAAAAEAAAABAAAAAQAAAAEAAAABAA' ... 'ABAAAAAQAAAAEAAAABAAAAAQAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'ST_Slope'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [59]:
px.histogram(df,x='ExerciseAngina',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>ExerciseAngina=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>ExerciseAngina=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAEAAAABAAAAAQAAAAEAAAAAAA' ... 'ABAAAAAAAAAAAAAAABAAAAAAAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'ExerciseAngina'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

Model training

In [60]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.drop('HeartDisease', axis=1), 
                                                    df['HeartDisease'], 
                                                    test_size=0.2, 
                                                    random_state=42,
                                                    stratify=df['HeartDisease'])

logistic regression

In [73]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
solver = ['lbfgs', 'newton-cg', 'liblinear', 'sag', 'saga','newton-cholesky']
best_solver = ''
test_score = np.zeros(len(solver))
for i, n in enumerate(solver):
    lr = LogisticRegression(solver=n,max_iter=1000).fit(x_train, y_train)
    test_score[i] = lr.score(x_test, y_test)
    if lr.score(x_test, y_test) == test_score.max():
        best_solver = n
print(best_solver)
lr = LogisticRegression(solver=best_solver)
lr.fit(x_train, y_train)
lr_pre= lr.predict(x_test)
print(f'logistic regression score : {accuracy_score(y_test, lr_pre)}')

c:\Users\shivp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

newton-cholesky
logistic regression score : 0.8695652173913043

c:\Users\shivp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [82]:
import pickle
with open('logistic.pkl', 'wb') as file:
    pickle.dump(lr, file)

support vactor machine (SVM)

In [74]:
from sklearn.svm import SVC
from sklearn.metrics import f1_score

kernals = {'linear':0, 'poly':0, 'rbf':0, 'sigmoid':0}
best=''
for i in kernals:
    svm = SVC(kernel=i).fit(x_train, y_train)
    yhat = svm.predict(x_test)
    kernals[i] = f1_score(y_test, yhat, average='weighted')
    if kernals[i] == max(kernals.values()):
        best = i
print(best)
svm = SVC(kernel=best)
svm.fit(x_train, y_train)
svm_pre = svm.predict(x_test)
print(f'SVM f1_score kernal({best}) : {f1_score(y_test, svm_pre, average="weighted")}')

linear
SVM f1_score kernal(linear) : 0.8633552559911067

In [81]:
with open('svm_model.pkl', 'wb') as file:
    pickle.dump(svm, file)

Decison Tree Classifier

In [76]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

dtree = DecisionTreeClassifier(class_weight='balanced')
param_grid = {
    'max_depth': [3,4, 5,6, 7,8],
    'min_samples_split': [2, 3,4],
    'min_samples_leaf': [1, 2, 3, 4],
    'random_state': [0,42]
}
grid_search = GridSearchCV(dtree,param_grid,cv=5)
grid_search.fit(x_train, y_train)
Ctree= DecisionTreeClassifier(**grid_search.best_params_,class_weight='balanced')
Ctree.fit(x_train, y_train)
Ctree_pre = Ctree.predict(x_test)   
print("decison tree accuracy:",accuracy_score(y_test, Ctree_pre))

decison tree accuracy: 0.8641304347826086

In [83]:
with open('DecisionTree.pkl', 'wb') as file:
    pickle.dump(Ctree, file)

RandomForest

In [77]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

rfc =RandomForestClassifier()

param_grid = {
    'n_estimators': [50,100,150,500],
    'max_features': ['sqrt', 'log2',None],
    'max_depth': [3, 6,9,19],
    'max_leaf_nodes': [3, 6, 9],
    
}
grid_search = GridSearchCV(rfc,param_grid)
grid_search.fit(x_train, y_train)
Rfctree = RandomForestClassifier(**grid_search.best_params_)
Rfctree.fit(x_train, y_train)
rfctree_pre = Rfctree.predict(x_test)
print("random forest accuracy:",accuracy_score(y_test, rfctree_pre))

random forest accuracy: 0.8804347826086957

In [84]:
with open('random_forest.pkl', 'wb') as file:
    pickle.dump(Rfctree, file)